name: Deploy CI

on:
  push:
    branches:
      - next

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: 'Setup Node.js'
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14

      - name: Install pnpm
        run: npm i pnpm -g

      - name: 'Install dependencies'
        run: pnpm install

      - name: Build
        env:
          CI: true
          GA_KEY: G-RMBLDHGL1N
          PROGRESS: none
          SITE_DEPLOY: 'TRUE'
        run: pnpm site

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
          force_orphan: true
